# CUDA
cuda_devices: '0'

# dataset
dataset:
  data_root: '/content/simplified_data_voxel_size_10_npz'
  augment_data: false
  max_faces: 8300

# model
load_model: '/content/drive/MyDrive/MeshNet_best.pkl'

# MeshNet
MeshNet:
  structural_descriptor:
    num_kernel: 64
    sigma: 0.2
  mesh_convolution:
    aggregation_method: 'Concat'  # Concat/Max/Average
  mask_ratio: 0.95
  dropout: 0.5
  num_classes: 2

# test config
batch_size: 64
retrieval_on: true
