# CUDA
cuda_devices: '0,1'   # multi-gpu training is available

# dataset
dataset:
  data_root: '/kaggle/input/manufacturing-dataset/simplified_data_voxel_size_10_npz'
  max_faces: 10000
  augment_data: False
  jitter_sigma: 0.01
  jitter_clip: 0.05

# result
ckpt_root: 'ckpt_root'

# MeshNet
MeshNet:
  structural_descriptor:
    num_kernel: 64
    sigma: 0.2
  mesh_convolution:
    aggregation_method: 'Concat'  # Concat/Max/Average
  mask_ratio: 0.95
  dropout: 0.5
  num_classes: 2

# train
seed: 0
lr: 0.005
momentum: 0.9
weight_decay: 0.0005
batch_size: 1
max_epoch: 200
optimizer: 'sgd' # sgd/adamw
scheduler: 'cos' # step/cos
milestones: [30, 60, 90]
gamma: 0.1
retrieval_on: False   # enable evaluating retrieval performance during training
save_steps: 10
